apiVersion: skaffold/v2beta2
kind: Config

# Dockerイメージのビルドに関する設定
build:
  tagPolicy:
    sha256: {}
  artifacts:
    # ビルドするイメージ
    - image: suzukey/pf-sakumon-frontend
      context: frontend/
    - image: suzukey/pf-sakumon-backend
      context: backend/
  local:
    useBuildkit: true

# デプロイに関する設定
deploy:
  kubectl:
    manifests:
      # MyContainers
      - k8s/frontend.yaml
      - k8s/backend.yaml
      - k8s/ingress.dev.yaml
      # Certificate
      # - 後日実装予定
      # Ingress
      - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/cloud/deploy.yaml
      # CertManager
      # - https://github.com/jetstack/cert-manager/releases/download/v0.15.0-beta.1/cert-manager.yaml
