kind: Namespace
apiVersion: v1
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # トレイリングスラッシュをなしで統一
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(.*)/$ /$1 redirect;
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
spec:
  tls:
    - hosts:
        - sakumon.localhost
      secretName: selfsigned-cert-tls
  rules:
    - host: sakumon.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: nuxt-frontend
              servicePort: 3000
          - path: /(api|rails)
            backend:
              serviceName: rails-backend
              servicePort: 3000
---
apiVersion: v1
data:
  use-forwarded-headers: "false"
  server-tokens: "false"
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
