apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  tls:
    - hosts:
        - sakumon.localhost
      secretName: certificate-tls
  rules:
    - host: sakumon.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: web-test
              servicePort: 80
