apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # トレイリングスラッシュをなしで統一
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(.*)/$ /$1 redirect;
spec:
  tls:
    - hosts:
        - sakumon.localhost
      secretName: selfsigned-cert-tls
  rules:
    - host: sakumon.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: echo1
              servicePort: 80
          - path: /2
            backend:
              serviceName: echo2
              servicePort: 80
