apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    # ACMEサーバーのURL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # ACME registrarionのためのEmailアドレス
    email: suzukei0208@gmail.com
    # ACMEアカウントの秘密鍵を格納するために使用されるシークレットの名前
    privateKeySecretRef:
      name: letsencrypt-staging
    # HTTP-01チャレンジプロバイダーの有効化
    solvers:
      # 空の'selector'は全てのドメインに一致することを意味します
      - selector: {}
        http01:
          ingress:
            class: nginx
