require:
  - rubocop-rails

AllCops:
  Exclude:
    - "bin/**"
    - "db/schema.rb"

Rails:
  Enabled: true

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 警告 120文字
# 禁止 160文字
Layout/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - "config/routes.rb"

# 1メソッドが20行を超えない
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# 1クラスが120行を超えない
Metrics/ClassLength:
  Max: 120
  Exclude:
    - "db/migrate/*.rb"

# デフォルトの6は強すぎるので緩める
Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - "db/migrate/*.rb"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*rb"

# ---------------------------
# rubocopに勧められたもの
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
